name: Build and Release Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y make zip jq
      - name: Build extension
        run: make
      - name: Locate built ZIP file
        id: find_zip
        run: |
          ZIP_FILE=$(ls *.zip | head -n 1)
          if [ -z "$ZIP_FILE" ]; then
            echo "No ZIP file found!"
            exit 1
          fi
          echo "ZIP_FILE=$ZIP_FILE" >> $GITHUB_ENV
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
      - name: Upload Build Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ZIP_FILE }}
          asset_name: ${{ env.ZIP_FILE }}
          asset_content_type: application/zip
